---
version: "3.3"

networks:
  net:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx-config/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
    networks:
      - net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  fava:
    build: ./fava
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./fava-data:/fava
